services:
  react:
    image: codhub-landing
    container_name: codhub-landing
    restart: on-failure
    build:
      context: ../
      dockerfile: .docker/dockerfile
      args:
        USER_ID: ${LOCAL_USER_ID:-1000}
        GROUP_ID: ${LOCAL_GROUP_ID:-1000}
    ports:
      - "5173:5173"
    volumes:
      - ../:/app
